### ISSUE TITLE
Add detailed scholar uptime in Player's tab

### ISSUE THREAD

**Issue by Rolmachine** [baaron4/GW2-Elite-Insights-Parser#229]
Hello,
Is it possible to add the detailed scholar uptime over the fight (just like it's done for, for instance, quickness or element of rage, in the player's tab)?
It would really help to tackle the healing issues :)

**Comment by Flomix** [comment]
that could only be guesstimated I guess, when you don't attack for 10 seconds noone can tell if you had scholar during that time or not

**Comment by EliphasNUIT** [comment]
You have scholar details in the damage stats table with the % of hits done under scholar and the power damage you gained from it.
![aaaa](https://user-images.githubusercontent.com/16018765/47426575-dd6bf300-d78d-11e8-8288-1900c83f9473.png)

Putting that on the boon graph is not possible because, well, it's not a buff, it's discrete data and we don't know what's going on between two points. Even if it was somehow possible to track, I'd still refuse adding it as it would be somewhat a "health tracking" albeit a minor one and ANet is clear on that part, no health tracking on players.
