### ISSUE TITLE
CSV file creation gets "Error while Performing Background operation"

### ISSUE THREAD

**Issue by Enko63** [baaron4/GW2-Elite-Insights-Parser#28]
When attempting to parse a evtc.zip file it creates the excel file with the column headers but then hangs and gets "Error while Performing Background operation".

Looking at the headers, is it possible to just export all of the tables to a csv file so we can grab whatever data we want?

**Comment by EliphasNUIT** [comment]
I've fixed the error, will be pushing it.

**Comment by baaron4** [comment]
Will look into trying to get all the tables in. Keep in mind it requires a rewrite of the table functions and will take time. CSVs are not the same format as html datatables

**Comment by Enko63** [comment]
Thanks. I could give you a list of the current values I grab but as I expand what I keep metrics on, those may change which is why having all of the tables available would be nice. We could probably narrow it down to the useful things to prevent having to produce too many tables. I wouldn't mind having a discord conversation just to go over ideas.

**Comment by baaron4** [comment]
Not seeing you in the discord however, Ive just added all the "Stats" tables to CSV generation. Gonna Look at adding Boons probably. If there are anymore tables then those that you would really need do speak up. I could add all the player dmg distributions and their minions and I could even write out all the data included in the graphs: However those are things Ill be putting on the back burner for now since I dont think theyd be used

**Comment by Enko63** [comment]
Ill join the discord on monday. Travelling atm. Will take a look at the
stats included. Thanks for the continued support. Nice to have a parser
thats still kept up to date since raidheroes guy is gone. Have you looked
into the positioning sata that merforga and delta were talking about?

**Comment by baaron4** [comment]
Ya once you get in the discord youll see the GIFs Eliphus has made for combat replays
