### ISSUE TITLE
Additional useful numbers

### ISSUE THREAD

**Issue by Quadellupine** [baaron4/GW2-Elite-Insights-Parser#39]
I'm not sure how possible it is to implement any of this because of arcs limitation, however here we go:

**Values similar to the onhover value of scholar for Glyph of Empowerment**
I imagine this to be similar to the scholar value implementation that's already there, but maybe I'm wrong.

**Values similar to the onhover value of scholar for flat stat increases like AP/EA/Banners**
This might be more complicated I'd imagine, because you basically need to know the players current stats, deduct AP/EA/Banners and then recalculate the damage they did with the new values. I'm not sure to what extent this would even be possible.

**Values similar to the onhover value of scholar for Spirits**
Since they don't trigger randomly anymore it might be easier now, as frost spirit can basically be seen as a 5% buff during it's uptime now, and sun procs a set amount of burn stacks during it's uptime? 

**Approximation of how much health got leeched by Kalla Elite of renegade:**
At the moment damage done by life leech can't be tracked apparently, but that's relevant to see how much for instance renegades Kalla elite contributed. However the life leech is a consistent value of something like 700 and has no ICD, so if it is possible to track the amount of hits that were done while a player had the buff, it is possible to approximate how much DPS it did I think. This would obviously become inaccurate if there was more than just Kalla's life leech going on. (Blood Magic Necros etc.)

At the moment, if you multiply group DPS with the encounter time it turns out to be less than the total bosshealth due to untracked damage, which is an interesting metric to add in general perhaps. (This is also how we currently approximate Kalla value)

Thanks for the phases release, this is now fully replacing raidheroes for me!

**Comment by EliphasNUIT** [comment]
GoE & Frost & Kalla -> possible, will need some work but should be fine. There are some important bugs to fix, some fractal support and get the 10s/30s dps graph before. I'll add this to the backlog, no ETA for now though ^^ GoE check how much damage was done during its uptime, Frost same, Kalla the number of hits done during its uptime, the presence of Vampiric Aura should not affect the result. We can also do the same for Vampiric Aura.

Sun is more difficult since we have no way of getting the expertise of a player. So we can say that you got approximatively X stacks of burn thanks to it, each stack ticked for XXX on average. I don't think we can do more than that.

AP/EA/Banners, this is extremely complicated. Same as Sun Spirit, we can say you did XXX power damage during its uptime which is X% of your total damage. From that you'll need to calculate it yourself using your character's stats.
Example: 

| Presence           	|   Damage done during its presence	| 
|----------------------	|---	|
| Nothing              	|   	|
| EA only              	|   	|
| AP only              	|   	|
| Strength only        	|   	|
| Disc only            	|   	|
| EA + AP              	|   	|
| EA + Disc            	|   	|
| EA + Str             	|   	|
| Ap + Str             	|   	|
| AP + Disc            	|   	|
| Str + Disc           	|   	|
| EA + AP + Disc       	|   	|
| EA + AP + Str        	|   	|
| EA + AP + Str + Disc 	|   	|

**Comment by Quadellupine** [comment]
Hello!

Yeah, i currently have my own small tool to calculate AP/EA/Banner value. But if you can't get stats then yeah, I can see how those are an issue. 

I was thinking how overlap of Vampiric Aura and Kalla Elite would affect the result, that's why I mentioned it.

**Comment by EliphasNUIT** [comment]
Kalla has been added to arc dps and Delta fixed the formula when Cat signaled it to me. I'll remove that part once the experimental build becomes the official build

**Comment by EliphasNUIT** [comment]
I'm closing this, as EA/Banners/AP/Sun Spirit are impossible to do without having the real stats, frost spirit and GoE are done.
I'll soon start working on adding all kind of modifiers (how much 20% you got with aegis, how much damage you got with the boons etc) for all traits, if possible
