### ISSUE TITLE
Intermittent failures on upload to DPS Reports when HTML and JSON is generated successfully.

### ISSUE THREAD

**Issue by anewhomegw2** [baaron4/GW2-Elite-Insights-Parser#458]
**Describe the bug**
A high failure rate of success kills are not being uploaded to DPS Reports and the JSON reports "One or more error has occurred".  The local HTML and local JSON has generated successfully - these are 'success' kills.

About 1/3 of the kills are not being uploaded to DPS Reports: Success Kills - 1678:
 577 failed upload
 1101 successfully uploaded 

**To Reproduce**
1. Open Elite Insights
2. Copy a large number of logs to be processed from the year "2020"
3. Parse all the logs
4. Errors generated.

Reprocessing the failed uploaded files individually will successfully upload.

**Screenshots**
Counts of logs not uploaded - it affects a wide variety of bosses:
![image](https://user-images.githubusercontent.com/56842723/78032324-bccda280-735c-11ea-8b01-731d8699ea8a.png)

**IMPORTANT: Provide Files**
[Logs.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/4409403/Logs.zip)
This is an example of the JSON/HTML that was generated that registered errors "One or more errors occured"

**Comment by EliphasNUIT** [comment]
After reading this, I've run your scenario on approximatively 1600 logs, everything worked fine. The fight being a success or not has no influence on how it is parsed or uploaded.
I don't really manage dps.report API, the process is simple, I upload the log and wait dps.report's answer. The error you are seeing happens when the request is closed unexpectedly, this could be because of connectivity loss or dps.report closing the connection. It is difficult to tell until I can reproduce this.
As everything else parses correctly, it is very likely that the problem is not on EI side, particularly when you say that trying again fixes the problem. I'll try running the same scenario later if I can reproduce it.

**Comment by anewhomegw2** [comment]
Is there a way, I can get a more detailed log from the tool to work out whats going on?

**Comment by EliphasNUIT** [comment]
I can send a better message when the upload process fails, when parsing fails you generally already have the necessary information to understand (if handled exception) or to share with the devs (otherwise) on the UI (or the console, if you are using that).

**Comment by anewhomegw2** [comment]
Yup- I'm using the console - happy for a log file to go into the same place where I'm generating the output "folder" - e.g. GW2Raidar_<date>.log

**Comment by anewhomegw2** [comment]
Tested dev version - works fine.
