### ISSUE TITLE
Mantras not showing in Rotation Tabs

### ISSUE THREAD

**Issue by Thorinori** [baaron4/GW2-Elite-Insights-Parser#589]
**Describe the bug**
Firebrand Mantras (Haven't tested for Mesmer yet) don't show in the rotation tabs of parsed reports. Only damage mantras show up in the damage report, but still doesn't show in the rotation.

**To Reproduce**
1. Use Mantra in game
2. Parse log
3. Mantra uses aren't in rotation, however if they were damage mantras they do show up in Outgoing Damage Distribution for the player that used them.

**File**
Files provided as zip (.html made with most recent release of the parser)
[Log_Files.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/7034672/Log_Files.zip)

Provided log used several mantras throughout a quick test fight, Echo of Truth is the damage component for Mantra of Truth and it is the only one that shows up in the log.

**Comment by LunusLupus** [comment]
Instant cast skills cannot inherently be shown in the rotation since they aren't sent as events by the server. Some are detected via workarounds, e.g. if they provide a unique effect that can be directly traced back to them (e.g. continuum split).

**Comment by EliphasNUIT** [comment]
Instant cast skills are not actually detected by arcdps, it can only detects skills with animations, "area skill activation will only count skills which have animations (no shouts, no instants) - not notified by server." from the arcdps page.

Instant cast skills are actually computed by EI based on their unique effects. As such the following mantras can't be tracked:
- Mantra of Liberation
- Mantra of Lore
- Mantra of Potence
- Mantra of Concentration
- Mantra of Distraction
- Mantra of Resolve

As they don't have unique effect (damage or unique buffs) associated to them.

We can track the followings:
- Mantra of Recovery (if you have the heal stats addon)
- Mantra of Solace (if you have the heal stats addon)
- Mantra of Flame
- Mantra of Truth
- Mantra of Pain

I believe those ones are not being shown anymore because I have not updated them for the "mantras don't need to be prepared anymore" patch.
You have send me a log with mantra of truth, if you have logs with the remaining, I can also add them.

**Comment by Thorinori** [comment]
Ah alright, thanks for the info! I can probably go make some logs with every Mantra in a little bit for you guys :)

**Comment by Thorinori** [comment]
[Mantra_Logs.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/7034975/Mantra_Logs.zip)

I decided to put these in a separate comment instead of editing the previous one to make sure it notified you. These should have Mantras of Flame, Truth, and Pain in them (As I said I currently don't have the heal stats addon so couldn't snag those ones, sorry)

**Comment by EliphasNUIT** [comment]
Thanks, added in bb1bac0e95ba6444db2c8eeed1ae1201626b3bce.
