### ISSUE TITLE
Missing Encounter Specific Buffs

### ISSUE THREAD

**Issue by EliphasNUIT** [baaron4/GW2-Elite-Insights-Parser#594]
__Sabetha__:
~~https://wiki.guildwars2.com/wiki/Time_Bomb~~
~~https://wiki.guildwars2.com/wiki/Sapper_Bomb_(effect)~~

__Slothasor__:
~~https://wiki.guildwars2.com/wiki/Nauseated~~
~~https://wiki.guildwars2.com/wiki/Volatile_Poison_(effect)~~
~~https://wiki.guildwars2.com/wiki/Magic_Transformation~~
~~https://wiki.guildwars2.com/wiki/Slippery_Slubling_(effect) (cm)~~
~~https://wiki.guildwars2.com/wiki/Fixated~~

__Bandit Trio__:
~~https://wiki.guildwars2.com/wiki/Environmentally_Friendly_(effect)~~

__Matthias__:
~~https://wiki.guildwars2.com/wiki/Corruption_(Matthias_Gabrel_effect)~~
~~https://wiki.guildwars2.com/wiki/Unstable_Blood_Magic~~
~~https://wiki.guildwars2.com/wiki/Zealous_Benediction_(effect)~~
~~https://wiki.guildwars2.com/wiki/Snowstorm_(effect)~~
~~https://wiki.guildwars2.com/wiki/Heat_Wave_(effect)~~
~~https://wiki.guildwars2.com/wiki/Downpour_(effect)~~
~~https://wiki.guildwars2.com/wiki/Unstable_(Matthias_Gabrel)~~
~~https://wiki.guildwars2.com/wiki/Unbalanced~~
~~https://wiki.guildwars2.com/wiki/Bloodstone_Bisque (cm)~~

__Keep Construct__:
~~https://wiki.guildwars2.com/wiki/Xera%27s_Embrace~~
~~https://wiki.guildwars2.com/wiki/Fixated_(Keep_Construct)~~
~~https://wiki.guildwars2.com/wiki/Gaining_Power~~
~~https://wiki.guildwars2.com/wiki/Crimson_Attunement (phantasm)~~
~~https://wiki.guildwars2.com/wiki/Radiant_Attunement (phantasm)~~

__Twisted Castle__:
~~https://wiki.guildwars2.com/wiki/Creeping_Pursuit~~

__Cairn__:
~~https://wiki.guildwars2.com/wiki/Gaze_Avoidance~~
~~https://wiki.guildwars2.com/wiki/Countdown (cm)~~

__Mursaat Overseer__:
~~https://wiki.guildwars2.com/wiki/Mursaat_Overseer%27s_Shield~~
~~https://wiki.guildwars2.com/wiki/Dispel_(effect)~~
~~https://wiki.guildwars2.com/wiki/Protect_(effect)~~
~~https://wiki.guildwars2.com/wiki/Claim_(effect)~~
~~https://wiki.guildwars2.com/wiki/Empowered_(Mursaat_Overseer)~~

__Samarog__:
~~https://wiki.guildwars2.com/wiki/Fixated (Sam, Guldhem, Rigom)~~
~~https://wiki.guildwars2.com/wiki/Inevitable_Betrayal (Big Green, Small Green)~~
~~https://wiki.guildwars2.com/wiki/Soul_Swarm~~

__Deimos__:
~~https://wiki.guildwars2.com/wiki/Unseen_Burden_(Deimos)~~
~~https://wiki.guildwars2.com/wiki/Form_Up_and_Advance!~~
~~https://wiki.guildwars2.com/wiki/Devour~~

__Soulless Horror__:
~~https://wiki.guildwars2.com/wiki/Unbridled_Fear~~
~~https://wiki.guildwars2.com/wiki/Exile%27s_Embrace~~
~~https://wiki.guildwars2.com/wiki/Fixated~~

__River of Souls__:
~~https://wiki.guildwars2.com/wiki/Rift_Force~~
~~https://wiki.guildwars2.com/wiki/Soul_Siphon_(effect)~~
~~Spirit Form~~
~~Mortal Coil~~
~~https://wiki.guildwars2.com/wiki/Mortal_Coil~~
~~https://wiki.guildwars2.com/wiki/Energy_Threshold~~

__Statue of Death__:
~~https://wiki.guildwars2.com/wiki/Empowered_(Statue_of_Death)~~
~~https://wiki.guildwars2.com/wiki/Soul_Digestion~~
~~https://wiki.guildwars2.com/wiki/Reclaimed_Energy~~
~~https://wiki.guildwars2.com/wiki/Mortal_Coil~~
~~https://wiki.guildwars2.com/wiki/Energy_Threshold~~

__Statue of Ice__:
~~https://wiki.guildwars2.com/wiki/Glaciate~~
~~https://wiki.guildwars2.com/wiki/Shield_of_Ice~~

__Statue of Darkness__:
~~https://wiki.guildwars2.com/wiki/Last_Grasp~~
~~https://wiki.guildwars2.com/wiki/Last_Grasp_(Eye_of_Fate)~~
~~https://wiki.guildwars2.com/wiki/Light_Carrier~~
~~https://wiki.guildwars2.com/wiki/Empowered_(Light_Thief)~~
~~https://wiki.guildwars2.com/wiki/Exposed_(Statue_of_Darkness)~~

__Dhuum__:
https://wiki.guildwars2.com/wiki/Soul_Shackle_(effect) -> won't add, its addition would be confusing as only one of the two players actually get the buff, the link is formed between giver and receiver. It is possible to make copies of the buff events and override dst/src as required, however this is impacting, as mechanics and combat replay do not expect duplicate events.
~~https://wiki.guildwars2.com/wiki/Hastened_Demise~~
~~https://wiki.guildwars2.com/wiki/Imminent_Demise~~
~~https://wiki.guildwars2.com/wiki/Lethal_Report~~
~~https://wiki.guildwars2.com/wiki/One-Track_Mind~~
~~https://wiki.guildwars2.com/wiki/Energy_Threshold~~
~~Echo's Pick up~~

__Conjured Amalgamate__:
~~https://wiki.guildwars2.com/wiki/Locked_On~~
~~https://wiki.guildwars2.com/wiki/Fixation~~

__Qadim__:
~~Wyvern Enrage~~
~~https://wiki.guildwars2.com/index.php?title=Mythwright_Surge~~
~~https://wiki.guildwars2.com/wiki/Power_of_the_Lamp~~
~~https://wiki.guildwars2.com/wiki/Unbearable_Flames~~
~~https://wiki.guildwars2.com/wiki/Parry_(effect)~~
~~https://wiki.guildwars2.com/wiki/Lamp_Bond~~
~~Resistance (Lava Elemental)~~
~~Shielded (Lava Elemental)~~

__Sabir__:
~~https://wiki.guildwars2.com/wiki/Eye_of_the_Storm_(Sabir)~~

__Qadim the Peerless__:
~~https://wiki.guildwars2.com/wiki/Flare-Up~~
~~https://wiki.guildwars2.com/wiki/Cleansed_Conductor~~
~~https://wiki.guildwars2.com/wiki/Enfeebled_Force~~
~~https://wiki.guildwars2.com/wiki/Backlashing_Beam~~
~~https://wiki.guildwars2.com/wiki/Erratic_Energy~~
~~https://wiki.guildwars2.com/wiki/Incorporeal~~
~~https://wiki.guildwars2.com/wiki/Clutched_by_Chaos~~
~~Poisoned Power~~

__Artsariiv__:
~~https://wiki.guildwars2.com/wiki/Corporeal_Reassignment~~
~~https://wiki.guildwars2.com/wiki/Determination_(Viirastra)~~

__Arkk__:
~~https://wiki.guildwars2.com/wiki/Diaphanous_Shielding~~
~~https://wiki.guildwars2.com/wiki/Cosmic_Meteor~~
~~https://wiki.guildwars2.com/wiki/Fixated (solar bloom)~~
~~https://wiki.guildwars2.com/wiki/Electrocuted~~

__Siax__:
~~https://wiki.guildwars2.com/wiki/Fixated_(Nightmare)~~

__Ensolyss__:
~~https://wiki.guildwars2.com/wiki/Determination~~

__Ai__;
~~https://wiki.guildwars2.com/wiki/Fixated_(Fear)~~ There are 4 different buffs, one for each fear

__Icebrood Construct__;
~~https://wiki.guildwars2.com/index.php?title=Hypothermia_(story_effect)~~

__Boneskinner__:
~~https://wiki.guildwars2.com/wiki/Tormenting_Aura~~

__Freezy__:
https://wiki.guildwars2.com/wiki/Fixated
~~https://wiki.guildwars2.com/wiki/Icy_Barrier~~

https://wiki.guildwars2.com/wiki/Essence_manipulation
~~https://wiki.guildwars2.com/wiki/Enraged_(200%25)~~
~~https://wiki.guildwars2.com/wiki/Enraged_(500%25)~~

Also, verify encounter specific mechanics/combat replay decorations that are buff apply/remove dependent and add them to the simulator.

**Comment by Linkaaaaa** [comment]
From the lists at: https://github.com/baaron4/GW2-Elite-Insights-Parser/blob/eaccbdb2a47d80890039d90ab6f9a4bb0e5de5a4/GW2EIEvtcParser/EIData/Buffs/Buff.cs#L359

Missing Enrages of:

Raids Bosses:
- Vale Guardian: https://wiki.guildwars2.com/wiki/Enraged_(200%25)
- Gorseval the Multifarious: https://wiki.guildwars2.com/wiki/Enraged_(200%25)
- Sabetha the Saboteur: https://wiki.guildwars2.com/wiki/Enraged_(500%25)
- Slothasor: https://wiki.guildwars2.com/wiki/Enraged_(200%25)
- Matthias Gabrel: https://wiki.guildwars2.com/wiki/Enraged_(200%25)
- Keep Construct: https://wiki.guildwars2.com/wiki/Enraged_(200%25)
- Xera: https://wiki.guildwars2.com/wiki/Enraged_(Xera)
- Cairn the Indomitable: https://wiki.guildwars2.com/wiki/Enraged_(Cairn_the_Indomitable)
- Mursaat Overseer: https://wiki.guildwars2.com/wiki/Enraged_(200%25)
- Samarog: https://wiki.guildwars2.com/wiki/Enraged_(500%25)
- Deimos: https://wiki.guildwars2.com/wiki/Enraged_(200%25)
- Soulless Horror: https://wiki.guildwars2.com/wiki/Enraged_(200%25)
- Conjured Amalgamate: https://wiki.guildwars2.com/wiki/Enraged_(200%25)
- Nikare: https://wiki.guildwars2.com/wiki/Enraged_(Nikare)
- Kenut: https://wiki.guildwars2.com/wiki/Enraged_(Nikare)
- Qadim: https://wiki.guildwars2.com/wiki/Enraged_(Qadim)
- Qadim - Ancient Invoked Hydra
- Qadim - Apocalypse Bringer
- Qadim - Wyvern Patriarch
- Qadim - Wyvern Matriarch
- Cardinal Adina: https://wiki.guildwars2.com/wiki/Enraged_(200%25)
- Cardinal Sabir: https://wiki.guildwars2.com/wiki/Enraged_(200%25)
- Qadim the Peerless: https://wiki.guildwars2.com/wiki/Enraged_(200%25)

Strikes:
- Freezie: https://wiki.guildwars2.com/wiki/Enraged_(200%25)

Fractals:
- Skorvald
- Arkk
- Specifically, all of the bosses can gain Enrage due to the instability

General Effects:

- Artsariiv: 
https://wiki.guildwars2.com/wiki/Corporeal_Reassignment
- Arkk: 
https://wiki.guildwars2.com/wiki/Diaphanous_Shielding
https://wiki.guildwars2.com/wiki/Cosmic_Meteor
- Essence Manipulation (all of them, they are used in the strikes)
https://wiki.guildwars2.com/wiki/Essence_manipulation

**Comment by Linkaaaaa** [comment]
Bandit trio

https://wiki.guildwars2.com/wiki/Target!
https://wiki.guildwars2.com/wiki/Slow_Burn

**Comment by Linkaaaaa** [comment]
- Sabir

https://wiki.guildwars2.com/wiki/Eye_of_the_Storm_(Sabir)

**Comment by EliphasNUIT** [comment]
Closing this, will open a new one if necessary.
