### ISSUE TITLE
Qadim platforms not correct in CM

### ISSUE THREAD

**Issue by Sejsel** [baaron4/GW2-Elite-Insights-Parser#610]
**Describe the bug**
In CM, some extra platforms are broken. This is not properly adjusted in the combat replay. At the very least, there is one fewer platform in destroyer phase.

**To Reproduce**
Do Qadim CM. Look at Combat Replay.

**Screenshots**
![image](https://user-images.githubusercontent.com/998408/146436090-2c8463b4-2189-4139-af75-3936716264dc.png)

**Comment by EliphasNUIT** [comment]
After watching some videos, it seems up-left platform is hidden during destroyer phase, it gets back during Qadim phases. I couldn't notice any additional differences, hydra and wyvern phases seem to have the same platforms available as in normal mode (minus the one Qadim's destroy as losing a platform in CM makes the platform crumble, instead of it being just fiery).

**Comment by EliphasNUIT** [comment]
Should be fixed in 9a261b3a42ba48a1e5e428af71b30c37be07a2b2. Please re-open this if you notice additional anomalies.

**Comment by Sejsel** [comment]
One more platform is missing in the wyvern phase, in normal mode there is 3 next to Qadim here.

![image](https://user-images.githubusercontent.com/998408/154566950-93a0a9f8-dc6c-4f02-9569-a93fd902c28f.png)

**Comment by EliphasNUIT** [comment]
Fixed in 76bcbd41dcff7e9cadec483defd72031e7a44c83.
