### ISSUE TITLE
WVW JSON logs produce odd players>combatReplayData>dc starting with version 2.48.0.0

### ISSUE THREAD

**Issue by Drevarr** [baaron4/GW2-Elite-Insights-Parser#675]
**Describe the bug**
Starting with version 2.48.0.0 wvw json logs have a combatReplayData>dc entry for all players.  Appears to be max integer value.

**Screenshots**
![image](https://user-images.githubusercontent.com/16168556/210916645-46a8df2d-a7ae-400f-8e97-b1cd8b3fef65.png)

**IMPORTANT: Provide Files**
Add the EVTC and/or HTML of the log related to this issue
[20221205-230253_detailed_wvw_kill.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/10356890/20221205-230253_detailed_wvw_kill.zip)

**Comment by Drevarr** [comment]
Likely related.  one down state, two death states.
![image](https://user-images.githubusercontent.com/16168556/210918830-820b6820-7c96-4bde-9dff-08255d023359.png)

**Comment by EliphasNUIT** [comment]
Hello,

What is the problem you are encountering? You have stated the appearance of additional values, what is the issue?

**Comment by EliphasNUIT** [comment]
The arrays in CombatReplay are for deciding how to represent the given Agent, if time in dc => do not draw, if time in down => show as downed, if time in dead => show as dead, otherwise show as normal. 
The extra padding has been added in order to avoid mis-representing the Agent by indicating the last known status and the first status. In your 2nd image you can see the CR data ends at 32681 while the final state is "dead" which ends at 32499, which means you'd assume the Agent is alive between 32499 and 32681 but that would be wrong. The extra paddings are here to indicate that the final state has not changed.

You can use this data in order to compute dead duration, dc duration, down duration, but not how many times a player got downed for example, for that you should always use "defenses" as this state array does not indicate stuff like vapor form.
However, even before this change, you should always sum the content as follow, assume you wish to measure duration in a specific phase, that starts in phaseStart and end in phaseEnd:
sum{max(min(phaseEnd, array[i][1]) - max(phaseStart, array[i][0], 0}
It was never guaranteed that the time values in those arrays would be between 0 and EncounterEnd, on the contrary, more often than not, it was not the case but I guess you noticed it when you got some crazy values. For example, on current, if you get downed or die during Xera/Deimos pre events, you'll naturally get negative time values.
The formula I've given is actually how I compute downDuration, deadDuration and dcDuration, so doing it yourself is kinda rendundant unless you wish to compute it on a custom time interval.

**Comment by Drevarr** [comment]
Thanks for the clarification and detailed response.  Will adjust accordingly.
